# -*- coding: utf-8 -*-
"""Project 139.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yzT2VNhe6fRoNY4MUQ4BJeluyqM6ZlQL
"""

!pip install kaggle

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d gspmoreira/articles-sharing-reading-from-cit-deskdrop

!unzip articles-sharing-reading-from-cit-deskdrop.zip

import pandas as pd
import numpy as np

df_shared_articles = pd.read_csv("shared_articles.csv")
df_users_interactions = pd.read_csv("users_interactions.csv")

df_users_interactions.head()

df_shared_articles = df_shared_articles[df_shared_articles['eventType'] == "CONTENT SHARED"]

print(len(df_shared_articles))
df_shared_articles.head()

def findTotalEvents(x):
  total_likes = df_users_interactions[(df_users_interactions["contentId"] == x["contentId"]) & (df_users_interactions["eventType"] == "LIKE")].shape[0]
  total_views = df_users_interactions[(df_users_interactions["contentId"] == x["contentId"]) & (df_users_interactions["eventType"] == "VIEW")].shape[0]
  total_bookmarks = df_users_interactions[(df_users_interactions["contentId"] == x["contentId"]) & (df_users_interactions["eventType"] == "BOOKMARK")].shape[0]
  total_follows = df_users_interactions[(df_users_interactions["contentId"] == x["contentId"]) & (df_users_interactions["eventType"] == "FOLLOW")].shape[0]
  total_comment_created = df_users_interactions[(df_users_interactions["contentId"] == x["contentId"]) & (df_users_interactions["eventType"] == "COMMENT CREATED")].shape[0]
  return total_likes + total_views + total_bookmarks + total_follows + total_comment_created

df_shared_articles["total_events"] = df_shared_articles.apply(findTotalEvents, axis=1)

df_shared_articles = df_shared_articles.sort_values('total_events', ascending = False)
df_shared_articles[['timestamp', 'authorSessionId', 'contentType', 'url', 'title' , 'text', 'lang' ,'total_events']].head(10)